### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by Willometers** [learn-co-curriculum/phase-3-active-record-crud-operations-lab#3]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by lizbur10** [comment]
Hi @Willometers ! I'm sorry to hear you're running into problems with this lab.

I am unable to recreate the issue so I am closing it for now.

If you are able to provide more detail about specifically what is missing I'll be happy to take another look.

Thanks for contributing to the Flatiron School curriculum! 💙
