### ISSUE TITLE
Confusing instructions

### ISSUE THREAD

**Issue by achardon** [learn-co-curriculum/phase-3-active-record-crud-operations-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/4332/assignments/135261?module_item_id=281146

### Concern

Hi! Just wanted to point out that on the last part of the instructions under 'Delete', the first bullet point describes a #destroy method, which I thought should mean it's an instance method. The only thing that worked to pass the test was using a class method (self.delete_by_id). 

### Suggested Changes

This is very minor, but it confused me, so maybe it's supposed to say .destroy instead of #destroy?

**Comment by ihollander** [comment]
Hi @achardon - thanks for flagging! I can see how this is confusing. You are correct that the tests require you to write a `self.delete_by_id` class method in the `Movie` class. The README is suggesting that when you implement that method, you should use the build-in `#destroy` instance method from Active Record, so you might end up with a method like this:

```rb
  # defining a class method .delete_by_id
  def self.delete_by_id(id)
    movie = Movie.find(id)
    # using the instance method #destroy
    movie.destroy
  end
```

We'll try to clear this up by improving the readme!

**Comment by achardon** [comment]
Oh that makes sense! Thanks for clearing that up. Appreciate it!
